fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Check Requirements File in sync
        entry: poetry export --format=requirements.txt --without-hashes --dev --output=requirements.txt
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: iSort
        entry: poetry run isort .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Security
        entry: poetry run bandit -r sparrow
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint -j 0 sparrow tests
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: poetry run flake8 sparrow tests
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy sparrow
        pass_filenames: false
        language: system
